version: 2.1
executors:
  go-build:
      docker:
        - image: gcr.io/pendo-dev/go-build:1.19
          auth:
            username: _json_key
            password: $GCR_JSON_KEY_FILE
jobs:
  test:
    executor:
      name: go-build
    steps:
      - checkout:
          path: ~/pendo-io/appwrap
      - run:
          name: Run tests
          command: cd ~/pendo-io/appwrap && go test -v ./...
workflows:
  version: 2
  default:
    jobs:
      - test
